name: Generate 3D Contribution Graph

on:
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: ssj52
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          filename: profile-3d.svg
          output_action: commit
          committer_branch: output
          committer_message: "chore: update 3d graph"
