name: Generate 3D Contribution Graph

on:
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate 3D Contribution Graph

    steps:
      - uses: actions/checkout@v3

      - uses: yoshi-code-bot/github-profile-3d-contrib@v0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          username: ssj52
          max_quantity_of_commits_color: 10
          type: "svg"

      - name: Push output
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: profile-3d-contrib
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
